print("hello, World!")
print("Altynai")
print("Akylai")
print("love")
print("Family")
print("mother")
print("summer")
print("september")
print("made")
print("work")
print("december")
print("Lesson")
print("money")
print("grandmohter")